# NumPy 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
conda install numpy


Solving environment: ...working... done

## Package Plan ##

  environment location: D:\anaconda

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | 3          |   3% 
conda-4.14.0         | 937 KB    | 5          |   5% 
conda-4.14.0         | 937 KB    | 6          |   7% 
conda-4.14.0         | 937 KB    | 8          |   9% 
conda-4.14.0         | 937 KB    | #          |  10% 
conda-4.14.0  

In [3]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.21.5


In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
print(np.amin)

<function amin at 0x000001DB62C1E550>


In [17]:
print(np.amin(arr))             ##min value
print(np.amax(arr))             ##max value
print(np.mean(arr))             ##mean value 
print(np.median(arr))           ##median value
print(np.ptp(arr))              ##range of values along an axis (peak to peak)
print(np.std(arr))              ##standard deviation
print(np.var(arr))              ##varience 
print(np.average(arr))          ##average  
print(np.percentile(arr,55))    ##percentile


1
10
5.5
5.5
9
2.8722813232690143
8.25
5.5
5.95


# numpy practical 

In [18]:
import numpy as np

In [19]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
#dimension of array
print(arr.ndim)

2


In [21]:
#shape of array
print(arr.shape)

(2, 4)


In [22]:
#to find data
print(arr.data)

# Random Number Generator using numpy

In [23]:
from numpy import random 
x=random.randint(100)
print(x)

48


In [24]:
from numpy import random 
x=random.randint(100)
print(x)

21


In [25]:
from numpy import random 
x=random.randint(100)
print(x)

31


In [26]:
from numpy import random 
x=random.randint(100)
print(x)

20


In [27]:
from numpy import random 
x=random.randint(100)
print(x)

9


In [28]:
from numpy import random 
x=random.randint(50)
print(x)

11


In [29]:
from numpy import random 
x=random.randint(50)
print(x)

17


In [30]:
from numpy import random 
x=random.randint(50)
print(x)

9


In [31]:
from numpy import random 
x=random.randint(50)
print(x)

13


In [32]:
from numpy import random 
x=random.randint()
print(x)

TypeError: randint() takes at least 1 positional argument (0 given)

In [34]:
from numpy import random 
x=random.rand()
print(x)

0.7577352425510469


In [36]:
from numpy import random 
x=random.randint(100,size=(10))
print(x)

[73 56 68 32 19  9 62 10 67 88]


In [37]:
#generate 2-d array with 3 rows, each row containing 5 random int value
from numpy import random 
x=random.randint(100,size=(3,5))
print(x)

[[95  5 12 91 87]
 [42 52 27 10 26]
 [19 27 91 91 13]]


In [38]:
from numpy import random 
x=random.randint(100,size=(3,5))
print(x)

[[50 37 59 82 38]
 [25 99 40 51 46]
 [85 30 69 74 95]]


In [41]:
from numpy import random 
random.seed(101)
x=random.randint(100,size=(3,5))
print(x)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


In [42]:
#creating 1-d list

list1 =[1,2,3]

#creating 1-d list vertical

list2=[[10],
      [20],
      [30]]

#create vector1

vector1= np.array(list1)
vector2= np.array(list2)

print("Horizontal Vector")
print(vector1)

print("------------")

print("Vertical vector ")
print(vector2)

Horizontal Vector
[1 2 3]
------------
Vertical vector 
[[10]
 [20]
 [30]]


In [45]:
import numpy as np

a=np.matrix('1 2;3 4')
print("via string input : \n",a,"\n\n")

#

b=np.matrix([[5,6,7],[4,6]])
b

via string input : 
 [[1 2]
 [3 4]] 




matrix([[list([5, 6, 7]), list([4, 6])]], dtype=object)

In [2]:
import numpy as np

In [3]:
a= [[6,7],[8,9]]

b=[[1,3],[5,7]]

print(np.dot(a,b))

print("----------")

print(np.dot(b,a))

[[41 67]
 [53 87]]
----------
[[30 34]
 [86 98]]


In [6]:
a=([[6,7],[8,9]])

np.transpose(a)


array([[6, 8],
       [7, 9]])

In [3]:
import numpy as np
data = [34,23,44,22,12,21,78,90,97,33,35,56,67,78,42,31,89,88,60,70]

#first quartile

Q1 = np.median(data[:10])

#third quartile

Q3 = np.median(data[10:])

#interquartile range 

IQR = Q3-Q1

print(IQR)

30.0


# Array Broadcasting in Numpy

In [4]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [5]:
a=np.array([1.0,2.0,3.0])
b= 2.0
a*b

array([2., 4., 6.])

# Calculate BMI

In [13]:
#height 

hg_in = [61,65,66,64,68,70,69,64,63,62,72]

#convert into numpy array 

ht_np = np.array(hg_in)

#convert height from inch to meter

ht_np= ht_np*0.0245

ht_np

array([1.4945, 1.5925, 1.617 , 1.568 , 1.666 , 1.715 , 1.6905, 1.568 ,
       1.5435, 1.519 , 1.764 ])

In [16]:
#weight 
wt_pd =[100,200,160,180,140,155,172,180,200,168,210]

#convert in array
wt_np= np.array(wt_pd)

#convert weight from pound to kg np

wt_np = wt_np*0.45

wt_np


array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 77.4 , 81.  , 90.  ,
       75.6 , 94.5 ])

In [17]:
#BMI

BMI = wt_np/(ht_np**2)
BMI

array([20.1474773 , 35.48817184, 27.53673573, 32.94525718, 22.69815489,
       23.71460871, 27.08386314, 32.94525718, 37.77715445, 32.76470392,
       30.36929057])

In [19]:
players = np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 77.4   ,
        81.    , 90.    , 75.6   , 94.5   ],
       [ 1.4945,  1.5925,  1.617 ,  1.568 ,  1.666 ,  1.715 ,  1.6905,
         1.568 ,  1.5435,  1.519 ,  1.764 ]])

In [20]:
players[0][2]

72.0

In [21]:
players[1]

array([1.4945, 1.5925, 1.617 , 1.568 , 1.666 , 1.715 , 1.6905, 1.568 ,
       1.5435, 1.519 , 1.764 ])

In [22]:
#team pose

pT = players.transpose()
pT

array([[45.    ,  1.4945],
       [90.    ,  1.5925],
       [72.    ,  1.617 ],
       [81.    ,  1.568 ],
       [63.    ,  1.666 ],
       [69.75  ,  1.715 ],
       [77.4   ,  1.6905],
       [81.    ,  1.568 ],
       [90.    ,  1.5435],
       [75.6   ,  1.519 ],
       [94.5   ,  1.764 ]])

In [23]:
pT.shape

(11, 2)

In [27]:
print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))


print(np.std(wt_np))

print(np.corrcoef(wt_np,ht_np))

76.29545454545455
77.4
839.25
13.384089172416873
[[1.         0.29456353]
 [0.29456353 1.        ]]


In [1]:
import numpy as np

In [6]:

length=[10,20,30,40,50,60,70,80,90,100]
length_array=np.array(length)
length_array

breadth=[10,20,30,40,50,60,70,80,90,100]
breadth_array=np.array(breadth)
breadth_array


area=length_array*breadth_array
area



array([  100,   400,   900,  1600,  2500,  3600,  4900,  6400,  8100,
       10000])